# If someone with write access comments "/build-deploy-preview" on a pull request, emit a repository_dispatch event
name: Build Deploy Preview

on:
  issue_comment:
    types: [created]

jobs:
  build-deploy-preview:
    runs-on: ubuntu-latest
    # Only run for PRs, not issue comments
    if: |
      github.event.issue.pull_request
    steps:

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APPSMITH_INTEGRATION_TESTING_ID }}
          private_key: ${{ secrets.APPSMITH_INTEGRATION_TESTING_KEY }}

      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          issue-type: pull-request
          commands: |
            build-deploy-preview